USE [master]
GO

/****** Object:  Database [ITPM]    Script Date: 5/1/2020 4:12:54 PM ******/
DROP DATABASE [ITPM]
GO

/****** Object:  Database [ITPM]    Script Date: 5/1/2020 4:12:54 PM ******/
CREATE DATABASE [ITPM]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'ITPM', FILENAME = N'E:\Program Files\Microsoft SQL Server\MSSQL13.MSSQLSERVER\MSSQL\DATA\ITPM.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'ITPM_log', FILENAME = N'E:\Program Files\Microsoft SQL Server\MSSQL13.MSSQLSERVER\MSSQL\DATA\ITPM_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [ITPM].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [ITPM] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [ITPM] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [ITPM] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [ITPM] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [ITPM] SET ARITHABORT OFF 
GO

ALTER DATABASE [ITPM] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [ITPM] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [ITPM] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [ITPM] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [ITPM] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [ITPM] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [ITPM] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [ITPM] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [ITPM] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [ITPM] SET  DISABLE_BROKER 
GO

ALTER DATABASE [ITPM] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [ITPM] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [ITPM] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [ITPM] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [ITPM] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [ITPM] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [ITPM] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [ITPM] SET RECOVERY FULL 
GO

ALTER DATABASE [ITPM] SET  MULTI_USER 
GO

ALTER DATABASE [ITPM] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [ITPM] SET DB_CHAINING OFF 
GO

ALTER DATABASE [ITPM] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [ITPM] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [ITPM] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [ITPM] SET QUERY_STORE = OFF
GO

USE [ITPM]
GO

ALTER DATABASE SCOPED CONFIGURATION SET LEGACY_CARDINALITY_ESTIMATION = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 0;
GO

ALTER DATABASE SCOPED CONFIGURATION SET PARAMETER_SNIFFING = ON;
GO

ALTER DATABASE SCOPED CONFIGURATION SET QUERY_OPTIMIZER_HOTFIXES = OFF;
GO

ALTER DATABASE [ITPM] SET  READ_WRITE 
GO


